apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: {{ .Release.Name }}-ai
  namespace: {{ .Release.Namespace }}

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-ai

  minReplicas: {{ .Values.aiops.hpa.minReplicas }}
  maxReplicas: {{ .Values.aiops.hpa.maxReplicas }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.aiops.hpa.targetCPUUtilizationPercentage }}