apiVersion: v1
kind: Secret

metadata:
  name: {{ .Release.Name }}-ai-secret
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  GEMINI_API_KEY: {{ .Values.aiops.secret.geminiApiKey | quote }}
  GEMINI_MODEL: {{ .Values.aiops.secret.geminiModel | quote }}
  APP_ENV: {{ .Values.aiops.secret.appEnv | quote }}