apiVersion: v1
kind: Service

metadata:
  name: pulseops-backend-service

spec:
  type: {{ .Values.backend.service.type }}

  selector:
    app: pulseops-backend

  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      protocol: TCP