apiVersion: v1
kind: Service

metadata:
  name: pulseops-frontend-service

spec:
  type: {{ .Values.frontend.service.type }}

  selector:
    app: pulseops-frontend

  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 5173
      protocol: TCP