{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: pulseops-ingress

spec:

  ingressClassName: nginx

  rules:

    - host: pulseops.local

      http:

        paths:

          - path: /

            pathType: Prefix

            backend:

              service:

                name: pulseops-frontend-service

                port:

                  number: 5173

          - path: /api

            pathType: Prefix

            backend:

              service:

                name: pulseops-backend-service

                port:

                  number: 8000

{{- end }}