"""
PulseOps AI Engine

Provides AI-powered incident analysis using
Google Gemini and rule-based recommendations.
"""

import os

import google.generativeai as genai
from recommendation_engine import generate_recommendations

# ==========================================================
# Configure Gemini
# ==========================================================

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)


MODEL_NAME = "gemini-2.5-flash"


# ==========================================================
# Prompt Builder
# ==========================================================

def build_prompt(
    service: str,
    severity: str,
    message: str,
    monitoring_data: dict,
) -> str:
    """
    Build prompt for Gemini AI.
    """

    return f"""
You are an expert DevOps Site Reliability Engineer.

Analyze this incident.

Service:
{service}

Severity:
{severity}

Incident:
{message}

Monitoring Data:
{monitoring_data}

Provide:

1. Executive Summary

2. Root Cause

3. Business Impact

4. Recommended Fix

5. Preventive Actions

Respond in concise technical language.
"""


# ==========================================================
# AI Analysis
# ==========================================================

def analyze_incident(
    service: str,
    severity: str,
    message: str,
    monitoring_data: dict,
):
    """
    Generate AI incident analysis.
    """

    recommendations = generate_recommendations(
        service,
        severity,
        message,
    )

    if not GEMINI_API_KEY:
        return {
            "summary": "Gemini API key not configured.",
            "severity": severity,
            "root_cause": "Unknown",
            "recommendations": recommendations,
        }

    try:

        model = genai.GenerativeModel(MODEL_NAME)

        prompt = build_prompt(
            service,
            severity,
            message,
            monitoring_data,
        )

        response = model.generate_content(prompt)

        return {
            "summary": response.text,
            "severity": severity,
            "root_cause": "Generated by Gemini AI",
            "recommendations": recommendations,
        }

    except Exception as exc:

        return {
            "summary": f"AI analysis failed: {exc}",
            "severity": severity,
            "root_cause": "Unavailable",
            "recommendations": recommendations,
        }