import os
from datetime import datetime
from typing import Any, Dict, List

import google.generativeai as genai
import httpx
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

# --------------------------------------------------
# Load Environment Variables
# --------------------------------------------------

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
PROMETHEUS_URL = os.getenv("PROMETHEUS_URL", "http://localhost:9090")
LOKI_URL = os.getenv("LOKI_URL", "http://localhost:3100")

if not GEMINI_API_KEY:
    raise RuntimeError("GEMINI_API_KEY not found in .env file")

# --------------------------------------------------
# Configure Gemini
# --------------------------------------------------

genai.configure(api_key=GEMINI_API_KEY)
gemini_model = genai.GenerativeModel("gemini-1.5-flash")

# --------------------------------------------------
# FastAPI
# --------------------------------------------------

app = FastAPI(
    title="PulseOps AI Incident Analyzer",
    description="AI-powered Incident Intelligence Platform",
    version="3.0.0",
)

# --------------------------------------------------
# Models
# --------------------------------------------------


class Incident(BaseModel):
    service: str
    severity: str
    message: str


class LogRequest(BaseModel):
    logs: List[str]


class AIResponse(BaseModel):
    summary: str
    root_cause: str
    severity: str
    recommendations: List[str]


# --------------------------------------------------
# Health
# --------------------------------------------------


@app.get("/")
def home():
    return {
        "project": "PulseOps",
        "service": "AI Incident Analyzer",
        "version": "3.0.0",
        "status": "running",
        "timestamp": datetime.utcnow().isoformat(),
    }


@app.get("/health")
def health():
    return {
        "status": "healthy",
        "gemini": bool(GEMINI_API_KEY),
        "prometheus": PROMETHEUS_URL,
        "loki": LOKI_URL,
        "timestamp": datetime.utcnow().isoformat(),
    }


# --------------------------------------------------
# Prometheus
# --------------------------------------------------


async def query_prometheus(query: str) -> Dict[str, Any]:
    """Execute a Prometheus instant query."""
    url = f"{PROMETHEUS_URL}/api/v1/query"

    async with httpx.AsyncClient(timeout=10) as client:
        response = await client.get(url, params={"query": query})
        response.raise_for_status()
        return response.json()


# --------------------------------------------------
# Loki
# --------------------------------------------------


async def query_loki(query: str) -> Dict[str, Any]:
    """Execute a Loki log query."""
    url = f"{LOKI_URL}/loki/api/v1/query"

    async with httpx.AsyncClient(timeout=10) as client:
        response = await client.get(url, params={"query": query})
        response.raise_for_status()
        return response.json()
    
# --------------------------------------------------
# Gemini AI Analysis
# --------------------------------------------------

async def generate_ai_analysis(
    incident: Incident,
    prometheus_data: Dict[str, Any],
    loki_data: Dict[str, Any],
) -> AIResponse:
    """
    Generate AI-powered incident analysis using Gemini.
    """

    prompt = f"""
You are an expert Site Reliability Engineer (SRE) and DevOps Engineer.

Analyze the following production incident.

Service:
{incident.service}

Severity:
{incident.severity}

Incident:
{incident.message}

Prometheus Metrics:
{prometheus_data}

Loki Logs:
{loki_data}

Provide:

1. Executive Summary
2. Most likely Root Cause
3. Final Severity (LOW / MEDIUM / HIGH / CRITICAL)
4. Top 5 Remediation Steps

Respond in plain English.
"""

    try:
        response = gemini_model.generate_content(prompt)

        text = response.text if hasattr(response, "text") else str(response)

        recommendations = []

        for line in text.splitlines():
            line = line.strip()

            if (
                line.startswith("-")
                or line.startswith("*")
                or line[:2].isdigit()
            ):
                recommendations.append(line.lstrip("-*0123456789. ").strip())

        if not recommendations:
            recommendations = [
                "Inspect Kubernetes events.",
                "Review Prometheus metrics.",
                "Check Loki logs.",
                "Verify latest deployment.",
                "Restart unhealthy pods if required.",
            ]

        return AIResponse(
            summary=text,
            root_cause="Generated by Gemini AI",
            severity=incident.severity.upper(),
            recommendations=recommendations[:5],
        )

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=f"Gemini analysis failed: {exc}",
        )


# --------------------------------------------------
# Collect Monitoring Data
# --------------------------------------------------

async def collect_monitoring_data() -> Dict[str, Any]:
    """
    Collect key metrics from Prometheus and Loki.
    """

    metrics = {}

    try:
        metrics["cpu"] = await query_prometheus(
            '100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)'
        )

        metrics["memory"] = await query_prometheus(
            '(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100'
        )

        metrics["pods"] = await query_prometheus(
            'up'
        )

    except Exception as exc:
        metrics["prometheus_error"] = str(exc)

    try:
        metrics["logs"] = await query_loki('{job="varlogs"}')

    except Exception as exc:
        metrics["loki_error"] = str(exc)

    return metrics

# --------------------------------------------------
# API Endpoints
# --------------------------------------------------

@app.get("/metrics")
async def metrics():
    """
    Return current monitoring data from Prometheus and Loki.
    """
    return await collect_monitoring_data()


@app.post("/analyze", response_model=AIResponse)
async def analyze_incident(incident: Incident):
    """
    Perform AI-powered incident analysis.
    """
    monitoring_data = await collect_monitoring_data()

    prometheus_data = {
        k: v for k, v in monitoring_data.items() if k != "logs"
    }

    loki_data = monitoring_data.get("logs", {})

    return await generate_ai_analysis(
        incident,
        prometheus_data,
        loki_data,
    )


@app.get("/summary")
async def incident_summary():
    """
    Generate an executive summary of the current platform state.
    """

    monitoring_data = await collect_monitoring_data()

    prompt = f"""
You are an SRE.

Summarize the current health of the platform based on these metrics.

Monitoring Data:

{monitoring_data}

Write a concise executive summary.
"""

    try:
        response = gemini_model.generate_content(prompt)

        return {
            "generated_at": datetime.utcnow().isoformat(),
            "summary": response.text,
        }

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=str(exc),
        )


@app.get("/root-cause")
async def root_cause():
    """
    Generate AI-based root cause analysis.
    """

    monitoring_data = await collect_monitoring_data()

    prompt = f"""
You are an experienced Site Reliability Engineer.

Based on the monitoring information below, identify the most probable root cause.

Monitoring Data:

{monitoring_data}

Return:

- Root Cause
- Impact
- Confidence
"""

    try:
        response = gemini_model.generate_content(prompt)

        return {
            "generated_at": datetime.utcnow().isoformat(),
            "analysis": response.text,
        }

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=str(exc),
        )


@app.get("/ai-status")
def ai_status():
    """
    Verify external integrations.
    """
    return {
        "gemini": bool(GEMINI_API_KEY),
        "prometheus": PROMETHEUS_URL,
        "loki": LOKI_URL,
        "version": "3.0.0",
    }