apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: pulseops
  namespace: argocd

spec:
  project: pulseops

  source:
    repoURL: https://github.com/bhargav761/pulseops.git
    targetRevision: main
    path: helm/pulseops

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: pulseops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true