# ====================================================
# PulseOps Helm Values
# ====================================================

backend:
  replicaCount: 2

  image:
    repository: pulseops-backend
    tag: v2
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 8000

frontend:
  replicaCount: 2

  image:
    repository: pulseops-frontend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 5173

prometheus:
  enabled: true

grafana:
  enabled: true

loki:
  enabled: true

promtail:
  enabled: true

ingress:
  enabled: true

hpa:
  enabled: true
config:
  prometheusUrl: "http://prometheus:9090/api/v1/query"
secret:
  apiKey: "pulseops-secret-key"  