name: Trivy Image Scan

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  trivy:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Backend Docker Image
        run: |
          docker build -t pulseops-backend:latest ./microservices/auth-service

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: pulseops-backend:latest
          format: table
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"